version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: bravi-avaliacao-2

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bravi-avaliacao-2
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/bravi-avaliacao-2
    depends_on:
      - mongodb

volumes:
  mongodb_data:
